apiVersion: kustomize.config.k8s.io/v1alpha1  # <-- Component notation
kind: Component

patchesJson6902:
  - target:
      version: v1
      kind: ApplicationSet
      name: cert-manager
    patch: |-
      - op: replace
        path: /spec/generators/0/matrix/generators/0/git/repoURL
        value: https://github.com/karectl/karectl.git
      - op: replace
        path: /spec/template/spec/source/repoURL
        value: https://github.com/karectl/karectl.git
      - op: replace
        path: /spec/generators/0/matrix/generators/0/git/revision
        value: main
      - op: replace
        path: /spec/template/spec/source/targetRevision
        value: main